# Generated by Django 4.0.2 on 2022-02-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
    ]
