# Generated by Django 4.0.2 on 2022-02-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentrepeatchore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentchore',
            options={'ordering': ['writed_at']},
        ),
        migrations.AlterModelOptions(
            name='commentrepeatchore',
            options={'ordering': ['writed_at']},
        ),
    ]
