# Generated by Django 4.0.2 on 2022-02-14 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0003_alter_invite_invitee_alter_invite_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_email', models.EmailField(max_length=254, null=True)),
                ('code', models.CharField(max_length=6, null=True)),
                ('using', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=10)),
                ('life_pattern', models.CharField(choices=[('AM', '아침형'), ('PM', '저녁형')], max_length=10)),
                ('disposition', models.CharField(choices=[('collective', '집단주의'), ('individual', '개인주의')], max_length=10)),
                ('mbti', models.CharField(choices=[('intj', 'INTJ'), ('intp', '\u200bINTP'), ('entj', 'ENTJ'), ('entp', 'ENTP'), ('infj', 'INFJ'), ('infp', 'INFP'), ('emfj', 'ENFJ'), ('enfp', 'ENFP'), ('istj', 'ISTJ'), ('isfj', 'ISFJ'), ('estj', 'ESTJ'), ('esfj', 'ESFJ'), ('istp', 'ISTP'), ('isfp', 'ISFP'), ('estp', 'ESTP'), ('esfp', 'ESFP')], max_length=5)),
                ('message', models.TextField(blank=True, max_length=30)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='houses.house')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
