# Generated by Django 4.0.2 on 2022-02-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='life_pattern',
            field=models.CharField(blank=True, choices=[('AM', '아침형'), ('PM', '저녁형')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, choices=[('intj', 'INTJ'), ('intp', '\u200bINTP'), ('entj', 'ENTJ'), ('entp', 'ENTP'), ('infj', 'INFJ'), ('infp', 'INFP'), ('emfj', 'ENFJ'), ('enfp', 'ENFP'), ('istj', 'ISTJ'), ('isfj', 'ISFJ'), ('estj', 'ESTJ'), ('esfj', 'ESFJ'), ('istp', 'ISTP'), ('isfp', 'ISFP'), ('estp', 'ESTP'), ('esfp', 'ESFP')], max_length=5),
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('provider', models.CharField(max_length=6)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
