# Generated by Django 4.0.2 on 2022-02-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emoji',
            field=models.SmallIntegerField(choices=[(1, 'Heart'), (2, 'Smile'), (3, 'Sad'), (4, 'Fire'), (5, 'Good')], default=1),
            preserve_default=False,
        ),
    ]
