# Generated by Django 4.0.2 on 2022-02-10 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='chore',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='choreinfo',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chores.category'),
        ),
        migrations.CreateModel(
            name='RepeatChore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignees', models.ManyToManyField(related_name='repeat_chores', related_query_name='has_repeat_chores', to=settings.AUTH_USER_MODEL)),
                ('days', models.ManyToManyField(to='chores.Day')),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chores.choreinfo')),
            ],
        ),
    ]
