# Generated by Django 4.0.2 on 2022-02-16 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0005_choreinfo_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='assignee',
        ),
        migrations.AddField(
            model_name='chore',
            name='assignees',
            field=models.ManyToManyField(related_name='chores', related_query_name='has_chore', to=settings.AUTH_USER_MODEL),
        ),
    ]
