# Generated by Django 4.0.2 on 2022-02-23 17:41

import chores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_remove_choreinfo_description_alter_choreinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatchore',
            name='allotcaion_method',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=chores.models.RepeatChore.allocation_method),
            preserve_default=False,
        ),
    ]
