# Generated by Django 4.0.2 on 2022-02-24 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_repeatchore_allotcaion_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatchore',
            name='planned_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
