# Generated by Django 4.0.2 on 2022-02-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_day_alter_chore_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chores.category'),
        ),
    ]
