# Generated by Django 4.0.2 on 2022-02-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_choreinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinfo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chores.category'),
        ),
    ]
