# Generated by Django 4.0.2 on 2022-02-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_remove_chore_assignee_chore_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={'ordering': ['-planned_at']},
        ),
    ]
