# Generated by Django 4.0.2 on 2022-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_repeatchore_planned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatchore',
            name='allotcaion_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fix'), (2, 'Order'), (3, 'Random')]),
        ),
    ]
