# Generated by Django 4.0.2 on 2022-02-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_alter_repeatchore_allotcaion_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeatchore',
            old_name='allotcaion_method',
            new_name='allocation_method',
        ),
    ]
