# Generated by Django 4.0.2 on 2022-02-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_disposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='life_pattern',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='message',
        ),
    ]
