# Generated by Django 4.0.2 on 2022-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_email', models.EmailField(max_length=254, null=True)),
                ('code', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
