# Generated by Django 4.0.2 on 2022-02-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauth',
            name='using',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disposition',
            field=models.CharField(choices=[('collective', '집단주의'), ('individual', '개인주의')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='life_pattern',
            field=models.CharField(choices=[('AM', '아침형'), ('PM', '저녁형')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(choices=[('intj', 'INTJ'), ('intp', '\u200bINTP'), ('entj', 'ENTJ'), ('entp', 'ENTP'), ('infj', 'INFJ'), ('infp', 'INFP'), ('emfj', 'ENFJ'), ('enfp', 'ENFP'), ('istj', 'ISTJ'), ('isfj', 'ISFJ'), ('estj', 'ESTJ'), ('esfj', 'ESFJ'), ('istp', 'ISTP'), ('isfp', 'ISFP'), ('estp', 'ESTP'), ('esfp', 'ESFP')], max_length=5),
        ),
    ]
