# Generated by Django 4.0.2 on 2022-02-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_socialuser_profile_socialuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialUser',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default=''),
        ),
    ]
