# Generated by Django 4.0.2 on 2022-02-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0003_alter_notice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='notices.notice')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_notice', related_query_name='notification_notice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notice__writed_at'],
            },
        ),
    ]
