# Generated by Django 4.0.2 on 2022-02-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favor', '0002_alter_favor_options'),
        ('notifications', '0003_notificationfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationfeedback',
            options={'ordering': ['-feedback__sended_at']},
        ),
        migrations.CreateModel(
            name='NotificationFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('favor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='favor.favor')),
            ],
            options={
                'ordering': ['-favor__sended_at'],
            },
        ),
    ]
