# Generated by Django 4.0.2 on 2022-02-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_invite_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favor', '0002_alter_favor_options'),
        ('notifications', '0004_alter_notificationfeedback_options_notificationfavor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationfavor',
            options={'ordering': ['favor__sended_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationfeedback',
            options={'ordering': ['feedback__sended_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationinvite',
            options={'ordering': ['invite__sended_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationnotice',
            options={'ordering': ['notice__writed_at']},
        ),
        migrations.AddField(
            model_name='notificationfeedback',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_feedback', related_query_name='notification_feedback', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationfavor',
            name='favor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='favor.favor'),
        ),
        migrations.AlterField(
            model_name='notificationinvite',
            name='invite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notificatoin', to='houses.invite'),
        ),
    ]
