# Generated by Django 4.0.2 on 2022-02-19 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationfavor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationfavor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationfeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationinvite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationnotice',
            options={},
        ),
        migrations.AddField(
            model_name='notificationfavor',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationfeedback',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationinvite',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationnotice',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationfeedback',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationinvite',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
