# Generated by Django 4.0.2 on 2022-02-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_invite_invitee_alter_invite_inviter'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notices', related_query_name='notice', to='houses.house'),
            preserve_default=False,
        ),
    ]
