# Generated by Django 4.0.2 on 2022-02-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_feedback_title'),
        ('notifications', '0002_notificationinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='feedbacks.feedback')),
            ],
            options={
                'ordering': ['feedback__sended_at'],
            },
        ),
    ]
