# Generated by Django 4.0.2 on 2022-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationfavor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfavor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationinvite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationnotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
